### PR TITLE
Update dependencies

### PR DESCRIPTION
**Pull request by kyessenov**
Signed-off-by: Kuat Yessenov <kuat@google.com>

### CODE REVIEW

**Comment by ldemailly** [comment]
can you wait for #42 ?

**Comment by ldemailly** [comment]
or maybe ask zack to add the control plane to his pr

**Comment by ZackButcher** [comment]
Just merge #42 first then this one.

**Comment by kyessenov** [comment]
Master is borked on istio/istio, so we should wait till it gets unborked.

**Comment by ZackButcher** [comment]
https://github.com/istio/vendor-istio/pull/42 should fix master too (it adds in the missing files).

**Comment by kyessenov** [comment]
PR #45 should have it

**Comment by ldemailly** [comment]
ah crap, it's out of date... need to be redone

**Pull request closed without merging**
