### PR TITLE
enable generation of adapter and template .proto files

### PR DESCRIPTION
**Pull request by theganyo**

### CODE REVIEW

**Comment by ldemailly** [comment]
not sure how you got conflict - maybe because I had to force push this repo

my apologies but can you redo the 
```
make depend.update DEPARGS="--update github.com/gogo/protobuf/protoc-min-version"
```
and update this PR accordingly ?

**Comment by ldemailly** [comment]
note that since my earlier comment I merged #7 but the istio/istio part hasn't happened yet
and we do need to serialize vendor changes please be patient
(if #7 doesn't pan out I'll revert it and you'll be next)

**Comment by ldemailly** [comment]
you're next - please go to vendor/ checkout master and rerun "make depend.update" in istio then update/redo this PR with the changes
(or rebase and rerun, you can not manually merge the lock file btw, it'd be invalid)

make sure `make vendor.check depend.status` doesn't error out before submitting the PRs

**Comment by theganyo** [comment]
replaced by https://github.com/istio/vendor-istio/pull/9

**Pull request closed without merging**
