### PR TITLE
Dependencies for istio #4421

### PR DESCRIPTION
**Pull request by objectiser**
Vendor dependencies to accompany https://github.com/istio/istio/pull/4421

Signed-off-by: Gary Brown <gary@brownuk.com>

### CODE REVIEW

**Comment by douglas-reid** [comment]
+1 on including this PR. We want the zipkin compat suite for (a) working tracing in Mixer and (b) ensuring that Mixer only generates traces when the headers already exist.

**Review by douglas-reid — APPROVED** [review]

**Comment by ldemailly** [comment]
let me know when istio/istio#4421 will be ready and I can merge this
we try to keep master of vendor in sync with master of istio so both PRs have to go in about the same time

heads up: if someone else makes a vendor change (for istio/api for instance) in the meantime you may have to redo this one

**Review by ldemailly — APPROVED** [review]

**Comment by objectiser** [comment]
@ldemailly ok thanks - will let you know.

**Comment by ldemailly** [comment]
someone did make vendor change in the meantime, you you need to redo it based on master

**Comment by ldemailly** [comment]
closing this, please redo after the others are done

**Pull request closed without merging**
