### PR TITLE
vendor cleanup of unused packages from istio/api

### PR DESCRIPTION
**Pull request by guptasu**
istio/istio changes to follow

istio/istio https://github.com/istio/istio/pull/4382

### CODE REVIEW

**Comment by ldemailly** [comment]
hey sorry can you try again after rebase, my other change is in

**Comment by guptasu** [comment]
@ldemailly rebased. PTAL

**Comment by ldemailly** [comment]
where did all the v1 mixer config go ? is this backward compatible/I don't see green, only red

**Review by ldemailly — APPROVED** [review]
lgtm as long as it works on istio/istio

**Pull request merged**
