### PR TITLE
Replace real glog with our custom shim to our logging story.

### PR DESCRIPTION
**Pull request by geeknoid**

### CODE REVIEW

**Comment by ldemailly** [comment]
please link the istio pr with all green tests including e2e rbac

**Comment by geeknoid** [comment]
https://github.com/istio/istio/pull/3759

**Comment by ldemailly** [comment]
please rebase the istio/istio PR and redo this one on top of master - tia

**Comment by ldemailly** [comment]
can you redo this from (latest, vendor's) master

**Review by ldemailly — APPROVED** [review]

**Pull request merged**
