### PR TITLE
Update go-control-plane

### PR DESCRIPTION
**Pull request by kyessenov**
Signed-off-by: Kuat Yessenov <kuat@google.com>

### CODE REVIEW

**Comment by ldemailly** [comment]
link the other pr ?

**Comment by ldemailly** [comment]
thanks I see it.

random note: can you get rid of these signed-off by...

**Review by ldemailly — APPROVED** [review]
lgtm but do not merge before the other pr is green

**Comment by ldemailly** [comment]
this needs to be a branch not a fork

**Comment by kyessenov** [comment]
Please merge here and in istio. No permissions.

**Comment by ldemailly** [comment]
merged, please update the sha in your istio pr
let's see if I ever learn as each time I merged without tests passing it dragged on for hours/days... but hopefully this will buck the trend

**Comment by ldemailly** [comment]
ps : you do have access btw, you did it last time

**Pull request merged**
