### PR TITLE
vendor_update_Feb17_2018

### PR DESCRIPTION
**Pull request by ldemailly**
ran dep ensure --update

### CODE REVIEW

**Comment by ldemailly** [comment]
istio/istio matching pr : https://github.com/istio/istio/pull/3588

**Comment by ldemailly** [comment]
matching lock file https://github.com/istio/istio/pull/3588/files#diff-bd247e83efc3c45ae9e8c47233249f18

**Comment by ldemailly** [comment]
@mandarjog

**Review by mandarjog — APPROVED** [review]
Ok

**Comment by ldemailly** [comment]
*cough* *cough* thanks for the accept but please don't merge - I was rerunning dep because the bot changed api

**Pull request merged**
