### PR TITLE
Changes for adding logadmin to vendor

### PR DESCRIPTION
**Pull request by gargnupur**
Corresponding Istio PR: https://github.com/istio/istio/pull/4806

### CODE REVIEW

**Review by ldemailly — APPROVED** [review]
thx, merge once the other PR is approved and passing

**Comment by ldemailly** [comment]
cc @kyessenov

**Comment by kyessenov** [comment]
Let me know if you need any help with getting vendor through @gargnupur

**Comment by gargnupur** [comment]
Thanks @kyessenov
@ldemailly, @kyessenov : I have approvals on main pr: https://github.com/istio/istio/pull/4806.

I see this error above: This pull request can be automatically merged by project collaborators
Can you please help me with how can I check this in?

**Comment by ldemailly** [comment]
we just got out of sync, #61 went in first, now we have to fix it

**Comment by gargnupur** [comment]
@ldemailly : Should we keep the sha of https://github.com/istio/vendor-istio/commit/1877ab0272b14e8cc52c9ba774edad85ee891941 so that when 4877 goes in, it will see the right sha?

**Pull request merged**
