### PR TITLE
Dependencies for istio #4421

### PR DESCRIPTION
**Pull request by objectiser**
Updated PR related to #36 which was previously signed off.

@ldemailly I think this can be applied now. Thanks.

Signed-off-by: Gary Brown <gary@brownuk.com>

### CODE REVIEW

**Comment by ldemailly** [comment]
ideally please link the PRs so it's clickable (as opposed to "istio #4421" which is not; or would link to the wrong repo, if there was an issue/pr #4421 in this one) by putting the url in the PR description:

https://github.com/istio/istio/pull/4421

(like you did in #36 before)

**Review by ldemailly — APPROVED** [review]

**Comment by ldemailly** [comment]
this needs to be in a branch btw, for the CI to pick it up in your other PR

**Comment by objectiser** [comment]
@ldemailly could you create a branch and I will switch the PR over to it?

**Comment by ldemailly** [comment]
I added you to have write permissions, accept the invite at
https://github.com/istio/vendor-istio/invitations

and then push your change to a branch in this repo first (then update your istio/istio pr once done so it points to here too)

ps: can you also update from latest master in istio/istio and redo make depend.update as I think another vendor change went in since you started? / just in case

**Comment by objectiser** [comment]
@ldemailly ok thanks - will try to get it sorted soon.

**Comment by ldemailly** [comment]
thanks ! and sorry the vendor process is quite painful,

suggestions/input welcome on https://github.com/istio/istio/issues/4746

**Comment by objectiser** [comment]
Closing in favour of #53

**Pull request closed without merging**
