### PR TITLE
Update Istio API to 3/27

### PR DESCRIPTION
**Pull request by diemtvu**

### CODE REVIEW

**Comment by loewenstein** [comment]
Related PR #39 

I followed the description in https://github.com/istio/istio/wiki/Vendor-FAQ#how-do-i-add--change-a-dependency (which is linked from https://github.com/istio/istio/blob/master/DEV-GUIDE.md#adding-dependencies) and the diff is looking different... I.e. it contains actual changes from https://github.com/istio/api not just a SHA change.

I am not sure what the correct change and/or process is, but apparently either this PR or the description in the wiki is not correct.

@kyessenov @ldemailly Could you shed light on this?

**Comment by kyessenov** [comment]
Yes, the diff includes changes both to the manifest (Godep files) and the
actual imported code. It appears there were changes to the istio/api repo
that may not have been imported yet in your case.

**Comment by diemtvu** [comment]
Frankly, I'm not sure on the procedure to update API neither. Looks like #39 save me some troubles, though guess I still need to add envoy packages, is that true?

**Comment by kyessenov** [comment]
Let me pull an update on go-control-plane and repeat this vendor update.

**Pull request closed without merging**
