### PR TITLE
Updating aws sdk and adding cloudwatch

### PR DESCRIPTION
**Pull request by narehayrapetyan**
Related PR adding cloudwatch mixer adapter - [link](https://github.com/istio/istio/pull/4617)

### CODE REVIEW

**Comment by ldemailly** [comment]
is this based off master ?

**Comment by narehayrapetyan** [comment]
@ldemailly yes, I rebased it on master. Actually I wasn't sure how to resolve the merge conflict on Gopkg.lock inputs-digest cause it looks like there's a commit on master that hasn't been pulled into the main project yet (788a4b4).

**Comment by narehayrapetyan** [comment]
Oh, just saw your comment on the other PR

**Comment by ldemailly** [comment]
both master's are now in sync (usually the window of out of sync should only be 1h at most but it took longer for the istio PR to get in that should have)

the way to resolve the conflict is just to pull, accept master's version, and then redo "make depend.update"

**Comment by ldemailly** [comment]
hey as mentioned in point 1 of https://github.com/istio/istio/wiki/Vendor-FAQ#how-do-i-add--change-a-dependency

you need to make a branch, for the istio/istio matching PR (https://github.com/istio/istio/pull/4617) to build. I added you as contributor so you can make a branch here

also can you accept the CLA

**Comment by narehayrapetyan** [comment]
great, yea let me do that. I didn't have permissions before, thanks for adding me.

**Comment by narehayrapetyan** [comment]
So I pushed the changes to a new branch in vendor istio. Is there anything else I need to do to retrigger the build? Also, do I need to reopen a PR to merge it in?

As far as the CLA I'm waiting for internal approval.

**Comment by ldemailly** [comment]
you need to push/update the PR so it shows to be from the branch in this repo instead of the branch in your fork; it may be easiest to do that by closing this PR and making a new PR from the branch

after which you need to use the sha in your original istio/istio PR

by checking out that branch and then git add vendor Gopkg.* in that PR

**Comment by ldemailly** [comment]
we can use #44

**Pull request closed without merging**
