### PR TITLE
Adding dep for json-patch

### PR DESCRIPTION
**Pull request by nmittler**

### CODE REVIEW

**Comment by nmittler** [comment]
@ZackButcher can you take a look?  I think @ldemailly is OOO

**Comment by kyessenov** [comment]
Rebase as you have a conflict with @ayj's quick vendor-update PR.

**Comment by kyessenov** [comment]
How come there is no Gopkg.toml file? Is the package transitively included?

**Comment by nmittler** [comment]
hmm .... I have no idea how to do this.  I'm closing this and will re-open another PR.

**Pull request closed without merging**
