### PR TITLE
Update github.com/envoyproxy/go-control-plane to get transparent socket support

### PR DESCRIPTION
**Pull request by rlenglet**
Update the `github.com/envoyproxy/go-control-plane` dependency to get the support for the `transparent` socket listener flag in LDS, as specified in https://github.com/envoyproxy/data-plane-api/pull/558.

Related: https://github.com/istio/proxy/pull/1338
Required by: https://github.com/istio/istio/pull/4654

Signed-off-by: Romain Lenglet <romain@covalent.io>

### CODE REVIEW

**Comment by rlenglet** [comment]
I signed it!

**Comment by kyessenov** [comment]
This might be dupe of https://github.com/istio/vendor-istio/pull/41?
@ldemailly can you also update go-control-plane in your pruning PR?

**Comment by rlenglet** [comment]
The version of `envoyproxy/data-plane-api` currently in vendor through `envoyproxy/go-control-plane` is slightly too old. I need the API change introduced in https://github.com/envoyproxy/data-plane-api/pull/558.

**Comment by kyessenov** [comment]
I think they both point to version 9fdf4bd79736a87c78b3d48b7baa84ea24be1c1a of go-control-plane which has the right API version. Getting vendor in is pretty tricky, since it requires serializing updates. I haven't finished my last update due to some issues, but me or @ldemailly could complete it, and you wouldn't need this PR.

**Comment by rlenglet** [comment]
@kyessenov OK, my bad, I didn't see that #41 was still open. Thanks!

**Comment by ldemailly** [comment]
it needs to be done on a branch

**Pull request closed without merging**
