### PR TITLE
vendor associated with change to toml file https://github.com/istio/i…

### PR DESCRIPTION
**Pull request by guptasu**
…stio/pull/3635/files#diff-836546cc53507f6b2d581088903b1785

After this vendor is in, I will update the submodule in Istio/Istio.

### CODE REVIEW

**Comment by guptasu** [comment]
@ldemailly PTAL

**Comment by ldemailly** [comment]
can you redo (I'm sorry!) "make depend.update" after you rebase once
https://github.com/istio/istio/pull/3678 is merged

that should cover most of this diff and should only leave you with istio/api changes (which btw we need to have a bot do)

**Comment by ldemailly** [comment]
done w the above PR
please note the Gopkg* are now copied into vendor/ for ease of history checking and comparing they match in istio/istio

**Comment by guptasu** [comment]
@ldemailly rebased and now I just have my 4 files. Good ?

**Comment by guptasu** [comment]
@ldemailly do I need to update the GoPkg* files too in this vendor repo ?

**Comment by ldemailly** [comment]
yes if you run the make depend.update it copies the 2 files in this repo so help sync/checks

i will add a target doing a diff but please add

**Comment by guptasu** [comment]
@ldemailly PTAL.

**Review by ldemailly — APPROVED** [review]

**Comment by ldemailly** [comment]
Thanks! Please rebase ur original pr

**Pull request merged**
